---
title: "homework4"
output: html_document
date: "2023-11-07"
---

```

```
install.packages("usethis")
library(usethis)
use_git_config(user.name="MeiqiXu",user.email="meiqi.xu.23@ucl.ac.uk")
use_git()
use_github()

```
```

library(tidyverse)
library(sf)
library(here)
library(janitor)
library(countrycode)

```

```
#读取csv文件，指定字符编码为"latin1"，na值为“ ”，跳过0行
HDI <- read_csv(here::here("HDR21-22_Composite_indices_complete_time_series.csv"),
                locale = locale(encoding = "latin1"),
                na = " ", skip=0)
World <- st_read("World_Countries_Generalized.shp")

HDIcols<- HDI %>%
  clean_names()%>%
  select(iso3, country, gii_2019, gii_2010)%>%
  mutate(difference=gii_2019-gii_2010)%>%
  #用countrycode()函数，将country列由初始的country.name转化为iso2c代码
  mutate(iso_code=countrycode(country, origin = 'country.name', destination = 'iso2c'))%>%
  #用countrycode()函数，将iso3列由初始的iso3代码转化为iso2c代码
  mutate(iso_code2=countrycode(iso3, origin ='iso3c', destination = 'iso2c'))

#连接空间数据和非空间数据
Join_HDI <- World %>% 
  clean_names() %>%
  left_join(., 
            HDIcols,
            by = c("iso" = "iso_code"))

Join_HDI_2 <- World %>% 
  clean_names() %>%
  left_join(., 
            HDIcols,
            by = c("country" = "country"))

Join_HDI_GB<-Join_HDI %>%
  filter(aff_iso=="GB")

Join_HDI_2_GB<-Join_HDI_2 %>%
  filter(aff_iso=="GB")


